version: '3.8'

name: solana-tg-bot

services:
  redis:
    container_name: 'stb_redis'
    image: 'eqalpha/keydb:latest'
    command: 'keydb-server /etc/keydb/keydb.conf --server-threads 2 --appendonly yes'
    restart: unless-stopped
    networks:
      - backend
    ports:
      - "6379:6379"
    volumes:
      - stb_redis_data:/data

volumes:
  stb_redis_data:

networks:
  backend:
